[package]
name = "catch22"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
ctrlc = "3.4.5"
pyo3 = "0.22.2"
rayon = "1.10.0"
rustfft = "6.2.0"

[build-dependencies]
bindgen = "0.70.1"
cc = "1.1.24"
cmake = "0.1.51"
